// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://segetcdohprrdklhutda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlZ2V0Y2RvaHBycmRrbGh1dGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTk3MzksImV4cCI6MjA3MzQzNTczOX0.ra_RT2LNk0VzbDZsewUTXKV9wbwH6Ao7_8WWLmr8fU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});